### ISSUE TITLE
Optimize sum calculation

### ISSUE THREAD

**Issue by AditiNarkar** [AditiNarkar/ilh-testing#1]
The current method calculates the sum of a large dataset by adding each element one by one. While this works, it may become slow when dealing with large datasets. We need a more efficient way to calculate the sum, whether through faster loops, alternative techniques, or optimizing performance to handle larger amounts of data smoothly.

**Comment by aaryaparadkar** [comment]
Lorem Ipsum

**Comment by aaryaparadkar** [comment]
This is a comment on the pull request!
